#!/usr/bin/env python3
import requests
"""
GET is one of the most common HTTP methods you’ll use when working with REST APIs. 
This method allows you to retrieve resources from a given API. 
GET is a read-only operation, so you shouldn’t use it to modify an existing resource.
"""
#simply sets a variable named api_url to the URL of a specific resource (a single todo item) in the JSONPlaceholder(fake API).
api_url = "https://jsonplaceholder.typicode.com/todos/1"
#requests.get() to send a GET request to /todos/1, which responds with the todo item with the ID 1
response = requests.get(api_url)
#call .json() on the response object to view the data that came back from the API
print(response.json())
# access response.status_code to see the HTTP status code
print(response.status_code)
# view the response’s HTTP headers with response.headers.
# This dictionary contains metadata about the response, such as the Content-Type of the response
#response has a Content-Type header set to application/json. This tells the user to parse the response as JSON
print(response.headers["Content-Type"])
#'application/json; charset=utf-8'